name: composite Actions Example
on:
  push:
    branches: [ master ]
  workflow_call:
jobs:
  node-js-workflow:
    runs-on: ubuntu-latest
    name: composite actions
    steps:
      - name: Install packages, test and code coverage
        uses: vignesh1424/python-Github-actions-workflow@main