name: composite Actions Example
on:
  pull_request:
    types: [closed]
    branches: [main, master]

jobs:
  ApplicantApi:
        uses: vignesh1424/python-Github-actions-workflow/.github/workflows/reusable-workflow.yml@main
        with:
          srcDir: "./src/APIs/"
          testDir: "./test"
          version: "3.8"