name: composite Actions Example
on:
  push:
    branches: [ master, main ]
jobs:
  node-js-workflow:

    
    runs-on: ubuntu-latest
    name: composite actions
    steps:
      - name: change directory
        run: |
          pwd
          ls -ltr
      - name: Install packages, build, test
        uses: vignesh1424/python-ci-workflow@main
        with:
          srcDir: "src/APIs/"
          testDir: "./test"
          version: "3.9"
          codeCoverage: "true"
