name: composite Actions Example
on:
  push:
    branches: [ master, main ]
jobs:
  node-js-workflow:

    
    runs-on: ubuntu-latest
    name: composite actions
    steps:
      - name: Install packages, build, test
        uses: vignesh1424/python-Github-actions-workflow/.github/workflows/reusable-workflow.yml@main
        with:
          srcDir: "./src/APIs/"
          testDir: "./test"
          version: "3.8"