name: CI Pipeline
on:

  workflow_call:
    inputs:
      apiName:
        required: true
        type: string
      applicationName:
        required: false
        type: string
      region:
        required: true
        type: string
      parameters:
        required: false
        type: string
      tags: 
        required: false
        type: string
      testDir:
        required: true
        type: string
        default: "./test"
      srcDir:
        required: true
        type: string
        default: "./src/APIs/" 
      environment:
        required: false
        type: string
        default: "Dev"
      deploy:
        required: false
        type: boolean
        default: true
      auth0:
        required: false
        type: boolean
        default: false
      auth0Scopes:
        required: false
        type: string
        default: ""
      version:
        required: false
        type: string
        default: "3.8"
      codeCoverage:
        description: run code coverage (true|false)
        type: string
        required: false
        default: "false"
jobs:
  ci:
    runs-on: ubuntu-latest
    environment: "Development"
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV_CICD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV_CICD }}
      ACM_AUTH_CIBT_COM: ${{ secrets.ACM_EC1_DEV_API_CASE_AUTH_CIBT_COM }}
      AWS_DEFAULT_REGION: ${{inputs.region}}
      MAP_MIGRATED: ${{secrets.AWS_MAP_SERVERID}}
      ENV: ${{ inputs.environment }}
      APPLICATION_NAME: ${{inputs.applicationName}}
      API_NAME: ${{inputs.apiName}}
      SRC_DIR: ${{inputs.srcDir}}
      TEST_DIR: ${{inputs.testDir}}
      TAGS: ${{ inputs.TAGS }}
      PARAMETERS: ${{inputs.parameters}}
      DEPLOY: ${{ inputs.deploy }}
      PAT: ${{ secrets.PAT_RICHARD }}
      PAT_USERNAME: richard-wharton_cibt
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DEV_CIBT_CLIENTCREDENTIALS_DOMAIN }}
      AUTH0_MGT_DOMAIN: ${{ secrets.AUTH0_DEV_CIBT_CLIENTCREDENTIALS_MGT_DOMAIN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_DEV_CIBT_CLIENTCREDENTIALS_CICD_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_DEV_CIBT_CLIENTCREDENTIALS_CICD_SECRET }}
      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
      AUTH0_SCOPES: ${{inputs.auth0scopes}}
      AUTH0: ${{inputs.auth0}}
      PYTHON_VERSION: ${{inputs.version}}
    steps:
      - name: Print all the github actions events
        uses: hmarr/debug-action@v2
      - uses: actions/checkout@v3
      - name: Python Build
        uses: vignesh1424/python-ci-workflow@main
        id: python-build
        with:
          srcDir: ${{ env.SRC_DIR }}
          testDir:  ${{ env.TEST_DIR }}
